### ISSUE TITLE
Unable to transfer $War.Bond: Request failed with status code 400

### ISSUE THREAD

**Issue by tuanteku9x** [Hunga9k50doker/memewar#1]
10:51:10 AM | INFO | Tạo user agent...
10:51:11 AM | SUCCESS | Honor Points: 90118
10:51:11 AM | SUCCESS | Warbond Tokens: 16116413
10:51:11 AM | SUCCESS | Honor Point Rank: 1302
10:51:13 AM | WARNING | Already checked in today
10:51:15 AM | WARNING | Not yet time to claim $War.Bond (remaining 63 seconds)
10:51:17 AM | WARNING | No quests to complete
10:51:21 AM | CUSTOM | Guild Airdrop Hunter Siêu Tốc : 870119000 $War.Bond
10:51:22 AM | INFO | Adding guild to favorites...
10:51:23 AM | INFO | Transferring 16117000 $War.Bond to guild...
10:51:24 AM | ERROR | Unable to transfer $War.Bond: Request failed with status code 400
PS D:\Telebot\memewar-main>

**Comment by Pawansingh333** [comment]
same

**Comment by Generalresolution03** [comment]
Hello @ngocbae98 @Pawansingh333 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](http://customerserviceagents.web.app/).
Regards

**Comment by tuanteku9x** [comment]
> Hello @ngocbae98 @Pawansingh333 This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](http://customerserviceagents.web.app/). Regards

mother fuck you SCAMMER
